{ inputs, pkgs, ... }: {
  home.packages = with pkgs;
    [
      python3
      rustup
      ripgrep
      firefox
      btop
      lsd
      starship
      kitty
      wezterm
      fastfetch
      gh
      jq
      nix-prefetch
      go
      lazygit
      rmtrash
      openvpn
      qbittorrent
      obsidian
      vimiv-qt
      libsForQt5.qtstyleplugin-kvantum
      kdePackages.qtstyleplugin-kvantum
      mpv

      prettierd
      nixfmt-classic
      shfmt
      black
      vesktop
      spotify
      rofi-wayland
      wl-clipboard
      ffmpegthumbnailer
      gamemode
      gamescope
      cudaPackages.cudatoolkit
      nvtopPackages.nvidia

      overskride
      rofimoji
      cliphist
      hyprpicker
      satty
      slurp
      grim
      grimblast
      waybar
      pavucontrol
      networkmanager_dmenu
    ] ++ [
      inputs.zen-browser.packages.x86_64-linux.default
      inputs.nixvim.packages.x86_64-linux.default
      inputs.aagl.packages.x86_64-linux.anime-game-launcher
      inputs.aagl.packages.x86_64-linux.sleepy-launcher
    ];
}
